"""make attraction 1to1 with destination, attraction_types array

Revision ID: 1b9c371f8566
Revises: 3505fc2039e9
Create Date: 2026-06-26 13:34:07.378753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1b9c371f8566'
down_revision: Union[str, Sequence[str], None] = '3505fc2039e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attraction', sa.Column('attraction_types', sa.JSON(), nullable=True))
    op.create_unique_constraint(None, 'attraction', ['destination_id'])
    op.drop_column('attraction', 'attraction_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attraction', sa.Column('attraction_type', postgresql.ENUM('temple', 'heritage', 'hiking', 'lake', 'viewpoint', name='attractiontype'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'attraction', type_='unique')
    op.drop_column('attraction', 'attraction_types')
    # ### end Alembic commands ###
