"""add entry fee table and remove the column of the attraction table 

Revision ID: 3505fc2039e9
Revises: 7388ef1f7083
Create Date: 2026-06-25 20:11:54.303136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3505fc2039e9'
down_revision: Union[str, Sequence[str], None] = '7388ef1f7083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry_fee',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('attraction_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('nepali', 'saarc', 'foreign', name='entrycategory'), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['attraction_id'], ['attraction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('address', sa.Column('place', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint(op.f('attraction_address_id_fkey'), 'attraction', type_='foreignkey')
    op.drop_constraint(op.f('attraction_food_cost_id_fkey'), 'attraction', type_='foreignkey')
    op.drop_constraint(op.f('attraction_accomodation_id_fkey'), 'attraction', type_='foreignkey')
    op.drop_column('attraction', 'food_cost_id')
    op.drop_column('attraction', 'address_id')
    op.drop_column('attraction', 'name')
    op.drop_column('attraction', 'entry_fee')
    op.drop_column('attraction', 'accomodation_id')
    op.drop_column('attraction', 'permit_required')
    op.drop_column('attraction', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attraction', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('attraction', sa.Column('permit_required', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('attraction', sa.Column('accomodation_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('attraction', sa.Column('entry_fee', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('attraction', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('attraction', sa.Column('address_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('attraction', sa.Column('food_cost_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('attraction_accomodation_id_fkey'), 'attraction', 'accommodation', ['accomodation_id'], ['id'])
    op.create_foreign_key(op.f('attraction_food_cost_id_fkey'), 'attraction', 'food_cost', ['food_cost_id'], ['id'])
    op.create_foreign_key(op.f('attraction_address_id_fkey'), 'attraction', 'address', ['address_id'], ['id'])
    op.drop_column('address', 'place')
    op.drop_table('entry_fee')
    # ### end Alembic commands ###
