"""add cascade on chat_message fk, fix datetime consistency

Revision ID: 47ca4483df14
Revises: 978405eab273
Create Date: 2026-06-27 11:05:26.763161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '47ca4483df14'
down_revision: Union[str, Sequence[str], None] = '978405eab273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chat_message_conversation_id_fkey'), 'chat_message', type_='foreignkey')
    op.create_foreign_key(None, 'chat_message', 'chat_conversation', ['conversation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_message', type_='foreignkey')
    op.create_foreign_key(op.f('chat_message_conversation_id_fkey'), 'chat_message', 'chat_conversation', ['conversation_id'], ['id'])
    # ### end Alembic commands ###
