"""add_destination_itinerary_table

Revision ID: 4974c79f5502
Revises: 47ca4483df14
Create Date: 2026-06-28 01:30:18.227295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4974c79f5502'
down_revision: Union[str, Sequence[str], None] = '47ca4483df14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destination_itinerary',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('destination_id', sa.Uuid(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('end_location', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('overnight_location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estimated_walking_hours', sa.Numeric(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('destination_itinerary')
    # ### end Alembic commands ###
