"""add_unique_review_and_saved_destinations

Revision ID: c41fa4cb8529
Revises: e93b28b9a13c
Create Date: 2026-08-06 18:24:19.524736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c41fa4cb8529'
down_revision: Union[str, Sequence[str], None] = 'e93b28b9a13c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Dedupe existing reviews: keep the newest row per (user_id, destination_id)
    # so the unique constraint below can be added.
    op.execute(
        """
        DELETE FROM review a USING review b
        WHERE a.user_id = b.user_id
          AND a.destination_id = b.destination_id
          AND (
              a.created_at < b.created_at
              OR (a.created_at = b.created_at AND a.id < b.id)
          )
        """
    )
    op.create_unique_constraint('uq_review_user_destination', 'review', ['user_id', 'destination_id'])
    op.create_unique_constraint('uq_saved_destinations_user_destination', 'saved_destinations', ['user_id', 'destination_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_saved_destinations_user_destination', 'saved_destinations', type_='unique')
    op.drop_constraint('uq_review_user_destination', 'review', type_='unique')
    # ### end Alembic commands ###
