"""add unique constraint on entry_fee

Revision ID: dc36e33d0056
Revises: 1b9c371f8566
Create Date: 2026-06-26 18:31:02.260134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dc36e33d0056'
down_revision: Union[str, Sequence[str], None] = '1b9c371f8566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'entry_fee', ['attraction_id', 'category'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('entry_fee_attraction_id_category_key'), 'entry_fee', type_='unique')
    # ### end Alembic commands ###
